### ISSUE TITLE
Write a program to find the sum, product , difference and division of two given numbers in any programming language.

### ISSUE THREAD

**Issue by tech-hima** [tech-hima/Hacktoberfest-2021#1]
Write code any language.

**Comment by Ritika457** [comment]
Please assign this to me.

**Comment by geryjuhasz** [comment]
I'll give it a go in PHP

**Comment by geryjuhasz** [comment]
please put sth in the repo so we can fork it

**Comment by zainulabideen1122** [comment]
Hy @tech-hima! I am able to do this task in python and C++. Can you assign also this task to me?
